.TH unix2dos 1 "unix2dos 4.1.2" "2010"

.SH NAME

unix2dos \- UNIX to DOS text file format converter

.SH SYNOPSYS

unix2dos [options] [\-c convmode] [\-o file ...] [\-n infile outfile ...]
.PP
Options:
.PP
[\-fhkLqV] [\-\-force] [\-\-help] [\-\-keepdate] [\-\-license] [\-\-quiet] [\-\-version]

.SH DESCRIPTION

.PP
Unix2dos converts text files in UNIX format to DOS format.
Binary files and non-regular files, such as soft links,
are automatically skipped, unless conversion is forced.

Unix2dos has a few conversion modes similar to unix2dos under SunOS/Solaris.

In DOS/Windows text files line endings exist out of a combination of two characters:
a Carriage Return (CR) followed by a Line Feed (LF).
In Unix text files line endings exists out of a single Newline character which
is equal to a DOS Line Feed (LF) character.

.SH OPTIONS

The following options are available:
.TP
.B \-c \-\-convmode convmode
Set conversion mode. Where convmode is one of:
.B ASCII, 7bit, ISO
with ASCII being the default.

.TP
.B \-f \-\-force
Force conversion of all files. Also binary files.

.TP
.B \-h \-\-help
Print online help.

.TP
.B \-k \-\-keepdate
Keep the date stamp of output file same as input file.

.TP
.B \-L \-\-license
Print software license.

.TP 
.B \-n \-\-newfile infile outfile ...
New file mode. Convert the infile and write output to outfile. File names
must be given in pairs and wildcard names should NOT be used or you WILL 
lose your files. 

.TP
.B \-o \-\-oldfile file ...
Old file mode. Convert the file and write output to it. The program 
default to run in this mode. Wildcard names may be used.

.TP
.B \-q \-\-quiet
Quiet mode. Suppress all warning and messages.

.TP
.B \-V \-\-version
Print version information.

.SH "CONVERSION MODES"

Conversion modes
.B ASCII
,
.B 7bit
, and
.B ISO
are similar to those of unix2dos under SunOS/Solaris.

.TP
.B ASCII
In this mode Unix line endings are converted to DOS line endings.

Although the name of this mode is ASCII, which is a 7 bit standard,
the actual mode is 8 bit.

.TP
.B 7bit
In this mode Unix line endings are converted to DOS line endings.
All 8 bit non-ASCII characters (with values from 128 to 255) are converted
to a space.

.TP
.B ISO
In this mode Unix line endings are converted to DOS line endings.  Characters
are converted from ISO character set ISO-8859-1 to DOS character set (code
page) CP437. ISO-8859-1 characters without CP437 equivalent, for which
conversion is not possible, are converted to a dot.  CP437 is mainly used in
the USA. In Western Europe CP850 is more standard.

Another option to convert text files between different encodings is to use
unix2dos in combination with iconv(1). Iconv can convert between a long list of
character encodings. Some examples:

Convert from Unix Latin-1 to DOS DOSLatinUS
.IP
.B iconv \-f ISO-8859-1 \-t CP437 in.txt | unix2dos > out.txt

Convert from Unix Latin-1 to DOS DOSLatin1
.IP
.B iconv \-f ISO-8859-1 \-t CP850 in.txt | unix2dos > out.txt

Convert from Unix Latin-1 to Windows WinLatin1
.IP
.B iconv \-f ISO-8859-1 \-t CP1252 in.txt | unix2dos > out.txt

Convert from Unix UTF-8 (Unicode) to Windows WinLatin1
.IP
.B iconv \-f UTF-8 \-t CP1252 in.txt | unix2dos > out.txt

See also <http://czyborra.com/charsets/codepages.html>
.br
and <http://czyborra.com/charsets/iso8859.html>.

.SH EXAMPLES

.LP
Get input from stdin and write output to stdout.
.IP
.B unix2dos

.LP
Convert and replace a.txt. Convert and replace b.txt.
.IP
.B unix2dos a.txt b.txt
.IP
.B unix2dos \-o a.txt b.txt

.LP
Convert and replace a.txt in ASCII conversion mode.
Convert and replace b.txt in 7bit conversion mode.
.IP
.B unix2dos a.txt \-c 7bit b.txt
.IP
.B unix2dos \-c ascii a.txt \-c 7bit b.txt

.LP
Convert and replace a.txt while keeping original date stamp.
.IP
.B unix2dos \-k a.txt
.IP
.B unix2dos \-k \-o a.txt

.LP
Convert a.txt and write to e.txt.
.IP
.B unix2dos \-n a.txt e.txt

.LP
Convert a.txt and write to e.txt, keep date stamp of e.txt same as a.txt.
.IP
.B unix2dos \-k \-n a.txt e.txt 

.LP
Convert and replace a.txt. Convert b.txt and write to e.txt.
.IP
.B unix2dos a.txt \-n b.txt e.txt
.IP
.B unix2dos \-o a.txt \-n b.txt e.txt

.LP
Convert c.txt and write to e.txt. Convert and replace a.txt.
Convert and replace b.txt. Convert d.txt and write to f.txt.
.IP
.B unix2dos \-n c.txt e.txt \-o a.txt b.txt \-n d.txt f.txt

.SH AUTHORS

Benjamin Lin \- <blin@socs.uts.edu.au>

Erwin Waterlander \- <waterlan@xs4all.nl>

Project page: http://www.xs4all.nl/~waterlan/dos2unix.html

SourceForge page: http://sourceforge.net/projects/dos2unix/

Freshmeat: http://freshmeat.net/projects/dos2unix

.SH SEE ALSO
dos2unix(1) iconv(1)

