=pod

=head1 NAAM

dos2unix - DOS/Mac naar Unix en vice versa tekstbestand formaat omzetter

=head1 OVERZICHT

    dos2unix [opties] [BESTAND ...] [-n BESTAND-IN BESTAND-UIT ...]
    unix2dos [opties] [BESTAND ...] [-n BESTAND-IN BESTAND-UIT ...]

=head1 BESCHRIJVING

Het Dos2unix pakket bevat toepassingen C<dos2unix> en C<unix2dos> om 
platte tekstbestanden in DOS of Mac formaat naar Unix om te zetten en
vice versa. Binaire bestanden en niet-reguliere bestanden, zoals
snelkoppelingen, worden automatisch overgeslagen, behalve als de omzetting
geforceerd wordt.

Dos2unix is gemodelleerd naar dos2unix onder SunOS/Solaris en heeft een aantal gelijke conversiemodi.

In DOS/Windows tekstbestanden bestaat een regeleinde uit een combinatie van twee
tekens: een 'Carriage Return' (CR) gevolgd door een 'Line Feed' (LF). In Unix
tekstbestanden bestaat een regeleinde uit een enkel 'Newline' teken die gelijk is
ann een DOS 'Line Feed' (LF) teken.
In Mac tekst bestanden, voor Mac OS X, bestaan regeleindes uit een
enkel 'Carriage Return' teken. Mac OS X is Unix gebaseerd en heeft dezelfde
regeleindes als Unix. 

=head1 OPTIES

=over 4

=item B<-ascii>

Converteer alleen regeleindes. Dit is de standaard coversie-modus.

=item B<-iso>

Conversie tussen DOS en ISO lettertekenreeks. Zie ook paragraaf
CONVERSIE MODI.

=item B<-1252>

Gebruik Windows codetabel 1252.

=item B<-437>

Gebruik DOS code page 437. This is the default code page used for ISO conversion.

=item B<-850>

Use DOS code page 850.

=item B<-7>

Convert 8 bit characters to 7 bit space.

=item B<-c, --convmode CONVMODUS>

Stel conversiemodus in. Waarbij CONVMODUS een is van:
I<ascii>, I<7bit>, I<iso>, I<mac>
met ascii als standaard instelling.

=item B<-f, --force>

Forceer omzetting van alle bestanden. Ook binaire bestanden.

=item B<-h, --help>

Laat help tekst zien.

=item B<-k, --keepdate>

Behoud de datum van het invoerbestand in het uitvoerbestand.

=item B<-L, --license>

Laat de software licentie zien.

=item B<-l, --newline>

Voeg een extra regeleinde toe.

B<dos2unix>: Alleen DOS regeleindes worden omgezet naar twee Unix regeleindes.
In Mac modus worden alleen Mac regeleindes omgezet naar twee Unix regeleindes.

B<unix2dos>: Aleen Unix regeleindes worden omgezet naar twee DOS regeleindes.
In Mac modus worden Unix regeleindes omgezet naar twee Mac regeleindes.

=item B<-n, --newfile BESTAND-IN BESTAND-UIT ...>

Nieuw bestand modus. Converteer bestand BESTAND-IN en schrijf naar bestand
BESTAND-UIT. Bestandsnamen moeten opgegeven worden in paren. Jokertekens
moeten NIET gebruikt worden, anders verlies je bestanden.

=item B<-o, --oldfile BESTAND ...>

Oud bestand modes. Converteer bestand BESTAND en overschrijf het.
Dit is de standaard modus. Jokertekens kunnen gebruikt worden.

=item B<-q, --quiet>

Stille werking. Onderdruk alle waarschuwingen.

=item B<-V, --version>

Laat versie informatie zien.

=back

=head1 CONVERSIE MODI

Conversie-modi I<ascii>, I<7bit>, en I<iso>
zijn gelijk aan die van dos2unix/unix2dos onder SunOS/Solaris.

=over 4

=item B<ascii>

B<dos2unix>: In deze modus worden DOS regeleindes omgezet naar Unix regeleindes.
Unix en Mac regeleindes worden niet veranderd.

B<unix2dos>: In deze modus worden Unix regeleindes omgezet naar DOS regeleindes.
DOS en Mac regeleindes worden niet veranderd.

Hoewel de naam van deze modus ASCII is, wat een 7 bit standaard is, is
de werkelijke modus 8 bit.

=item B<mac>

B<dos2unix>: In deze modus worden Mac regeleindes omgezet in Unix regeleindes.
DOS en Unix regeleindes worden niet omgezet. U kunt ook de opdracht C<mac2unix>
gebruiken om dos2unix in Mac modus uit te voeren.

B<unix2dos>: In deze modus worden Unix regeleindes omgezet in Mac regeleindes.
DOS en Mac regeleindes worden niet omgezet. U kunt ook de opdracht  C<unix2mac>
gebruiken om unix2dos in Mac modus uit te voeren.


=item B<7bit>

Alle 8 bit niet-ASCII lettertekens (met waardes van 128 t/m 255) worden omgezet
naar een spatie. 7bit modus can gecombineerd worden met B<ascii> en B<mac> modus.

=item B<iso>

Lettertekens worden omgezet tussen de DOS lettertekenreeks (codetabel) CP437
en ISO lettertekenreeks ISO-8859-1 op Unix. CP437 tekens zonder gelijkwaardig ISO-8859-1
teken, waarvoor geen omzetting mogelijk is, worden omgezet in een punt. Het zelfde
geldt voor ISO-8859-1 tekens zonder CP437 tegenhanger. CP437 wordt met name in
de VS gebruikt. In West Europa is CP850 meer gebruikelijk.
Iso modus can gecombineerd worden met B<ascii> en B<mac> modus.

Een andere optie om tekst bestanden om te zetten naar andere coderingen is om
dos2unix in combinatie met iconv(1) te gebruiken. Iconv kan omzetten tussen
een lange lijst letterteken-coderingen. Enkele voorbeelden:


Omzetten van DOS DOSLatinUS naar Unix Latin-1

    dos2unix -c iso -n in.txt out.txt
    of
    iconv -f CP437 -t ISO-8859-1 in.txt | dos2unix > uit.txt

Omzetten van DOS DOSLatin1 naar Unix Latin-1

    iconv -f CP850 -t ISO-8859-1 in.txt | dos2unix > uit.txt

Omzetten van Windows WinLatin1 naar Unix Latin-1

    iconv -f CP1252 -t ISO-8859-1 in.txt | dos2unix > uit.txt

Omzetten van Windows WinLatin1 naar Unix UTF-8 (Unicode)

    iconv -f CP1252 -t UTF-8 in.txt | dos2unix > uit.txt

Omzetten van Windows UTF-16 (Unicode) naar Unix UTF-8 (Unicode)

    iconv -f UTF-16 -t UTF-8 in.txt | dos2unix > uit.txt

Omzetten van Unix Latin-1 naar DOS DOSLatinUS

    unix2dos -c iso -n in.txt out.txt
    of
    unix2dos < in.txt | iconv -f ISO-8859-1 -t CP437 > uit.txt

Omzetten van Unix Latin-1 naar DOS DOSLatin1

    unix2dos < in.txt | iconv -f ISO-8859-1 -t CP850 > uit.txt

Omzetten van Unix Latin-1 naar Windows WinLatin1

    unix2dos < in.txt | iconv -f ISO-8859-1 -t CP1252 > uit.txt

Omzetten van Unix UTF-8 (Unicode) naar Windows WinLatin1

    unix2dos < in.txt | iconv -f UTF-8 -t CP1252 > uit.txt

Omzetten van Unix UTF-8 (Unicode) naar Windows UTF-16 (Unicode)

    unix2dos < in.txt | iconv -f UTF-8 -t UTF-16 > uit.txt

Zie ook L<http://czyborra.com/charsets/codepages.html>
en L<http://czyborra.com/charsets/iso8859.html>.

=back

=head1 UNICODE

Er bestaan verschillende Unicode coderingen. Op
Unix/Linux zijn Unicode bestanden meestal in UTF-8 codering gecodeerd.
UTF-8 is compatibel met ASCII. UTF-8 bestanden kunnen DOS, Unix of
Mac regeleindes hebben. Dos2unix/unix2dos kan gerust op UTF-8 bestanden
uitgevoerd worden. Op Windows wordt meestal UTF-16 codering gebruikt
voor Unicode. Dos2unix/unix2dos zou niet uitgevoerd moeten worden op
UTF-16 bestanden. UTF-16 bestanden worden automatisch overgeslagen,
omdat het binaire bestanden zijn.

=head1 VOORBEELDEN

Lees invoer van 'stdin' en schrijf uitvoer naar 'stdout'.

    dos2unix
    dos2unix -l -c mac

Omzetten en vervangen a.txt. Omzetten en vervangen b.txt.

    dos2unix a.txt b.txt
    dos2unix -o a.txt b.txt

Omzetten en vervangen a.txt in ascii conversie modus. 

    dos2unix a.txt

Omzetten en vervangen a.txt in ascii conversie modus.
Omzetten en vervangen b.txt in 7bit conversie modus.

    dos2unix a.txt -c 7bit b.txt
    dos2unix -c ascii a.txt -c 7bit b.txt

Omzetten a.txt van Mac naar Unix format.

    dos2unix -c mac a.txt
    mac2unix a.txt

Omzetten a.txt van Unix naar Mac format.

    unix2dos -c mac a.txt
    unix2mac a.txt

Omzetten en vervangen a.txt met behoud van originele datum.

    dos2unix -k a.txt
    dos2unix -k -o a.txt

Omzetten a.txt en schrijf naar e.txt.

    dos2unix -n a.txt e.txt

Omzetten a.txt en schrijf naar e.txt, behoud datum e.txt gelijk aan a.txt.

    dos2unix -k -n a.txt e.txt 

Omzetten en vervangen a.txt. Omzetten b.txt en schrijf naar e.txt.

    dos2unix a.txt -n b.txt e.txt
    dos2unix -o a.txt -n b.txt e.txt

Omzetten c.txt en schrijf naar e.txt. Omzetten en vervangen a.txt.
Omzetten en vervangen b.txt. Omzetten d.txt en schrijf naar f.txt.

    dos2unix -n c.txt e.txt -o a.txt b.txt -n d.txt f.txt

=head1 LOKALISATIE

=over 4

=item B<LANG>

The primaire taal wordt geselecteerd met de omgevingsvariabele LANG. De LANG
variabele bestaat uit verschillende onderdelen. Het eerste deel is in kleine
letters de taalcode. Het tweede deel is optioneel en is de landcode in
hoofdletters, voorafgegaan door een laag streepje. Er is ook een optioneel
derde deel: lettertekenreeks-codering, voorafgegaan door een punt. Enkele voorbeelden
voor een POSIX staandaard shell:

    export LANG=nl               Nederlands
    export LANG=nl_NL            Nederlands, Nederland
    export LANG=nl_BE            Nederlands, België
    export LANG=es_ES            Spaans, Spanje
    export LANG=es_MX            Spaans, Mexico
    export LANG=en_US.iso88591   Engels, VS, Latin-1 codering
    export LANG=en_GB.UTF-8      Engels, GB, UTF-8 codering

Voor een complete lijst van taal- en landcodes zie de gettext handleiding:
L<http://www.gnu.org/software/gettext/manual/gettext.html#Language-Codes>

Op Unix systemen kunt u de opdracht locale(1) gebruiken om specifieke
lokalisatie informatie te verkrijgen.

=item B<LANGUAGE>

Met de omgevingsvariabele LANGUAGE kunt u een prioriteitenlijst specificeren
van talen, gescheiden door dubbele punten. Dos2unix geeft voorkeur aan
LANGUAGE boven LANG. Bijvoorbeeld, eerst Nederlands en dan Duits: C<LANGUAGE=nl:de>.
U moet eerst lokalisatie in werking stellen, met het instellen van LANG (of LC_ALL)
in een waarde ongelijk aan "C", voordat u een talen prioriteitenlijst kunt
gebruiken via de LANGUAGE variabele. Zie ook de gettext handleiding:
L<http://www.gnu.org/software/gettext/manual/gettext.html#The-LANGUAGE-variable>

Er is voor Esperanto een speciaal taal bestand in x-methode formaat. X-methode
kan gebruikt worden op systemen die niet Latin-3 of Unicode codering ondersteunen.
Maak LANGUAGE gelijk aan "eo-x:eo".

Als u een taal kiest die niet beschikbaar is worden de standaard
Engelse berichten gebruikt.

=item B<DOS2UNIX_LOCALEDIR>

Met de omgevingsvariabele DOS2UNIX_LOCALEDIR kan de LOCALEDIR gebruikt tijdens
compilatie worden overstemd. LOCALEDIR wordt gebruikt om de taalbestanden te
vinden. De GNU staandaard waarde is C</usr/local/share/locale>. De optie "-V"
laat de gebruikte LOCALEDIR zien.

Voorbeeld (POSIX shell):

    export DOS2UNIX_LOCALEDIR=$HOME/share/locale

=back

=head1 AUTEURS

Benjamin Lin - <blin@socs.uts.edu.au>
Bernd Johannes Wuebben (mac2unix modus) - <wuebben@kde.org>
Erwin Waterlander - <waterlan@xs4all.nl>

Project pagina: L<http://www.xs4all.nl/~waterlan/dos2unix.html>

SourceForge pagina: L<http://sourceforge.net/projects/dos2unix/>

Freshmeat: L<http://freshmeat.net/projects/dos2unix>

=head1 ZIE OOK

iconv(1)

=cut
